trigger:
- master

# using ubuntu latest vmImage
pool:
  vmImage: 'ubuntu-latest'

pr: 'none'

stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sulavAryalpipeLineDemo'
              organization: '042020-dotnet-uta'
              scannerMode: 'MSBuild'
              projectKey: '042020-dotnet-uta_sulavAryal-repo0'
              projectName: 'sulavAryal-repo0'
          - script: dotnet build 'Project 0_Working\ConsoleShopper.UI\ConsoleShopper.UI.csproj'
          - script: echo 'Project built'
          - script: dotnet test --no-build 'Project 0_Working\ConsoleShopper.Tests\ConsoleShopper.Tests.csproj'