# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'Project0_SonarCloud'
              organization: '042020-dotnet-uta'
              scannerMode: 'MSBuild'
              projectKey: '042020-dotnet-uta'
              projectName: 'sulavAryal-repo0'
          - script: dotnet build 'Project 0_Working\ConsoleShopper.UI\ConsoleShopper.UI.csproj'
          - script: echo 'Project built'
          - script: dotnet test 'Project 0_Working\ConsoleShopper.Tests\ConsoleShopper.Tests.csproj'
          - task: SonarCloudAnalyze@1
      - job: 'publish'
        dependsOn: 'build'
        steps:
          - script: dotnet publish 'Project 0_Working\'ConsoleShopper.sln'
          